<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    private $data = [
        [
            'id'        => 1,
            'parent'    => null,
            'name'      => 'Handle all Organization',
            'name_l'    => 'হ্যান্ডেল সকল প্রকল্প',
            'web'       => '',
            'app'       => '',
            'web_icon'  => '',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 2,
            'parent'    => null,
            'name'      => 'Handle all Branch',
            'name_l'    => 'হ্যান্ডেল সকল শাখা',
            'web'       => '',
            'app'       => '',
            'web_icon'  => '',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 3,
            'parent'    => null,
            'name'      => 'Save / Update',
            'name_l'    => 'সেভ / আপডেট',
            'web'       => '',
            'app'       => '',
            'web_icon'  => '',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 4,
            'parent'    => null,
            'name'      => 'Block / Unblock',
            'name_l'    => 'ব্লক / আনব্লক',
            'web'       => '',
            'app'       => '',
            'web_icon'  => '',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 5,
            'parent'    => null,
            'name'      => 'Delete',
            'name_l'    => 'ডিলিট',
            'web'       => '',
            'app'       => '',
            'web_icon'  => '',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 6,
            'parent'    => null,
            'name'      => 'Dashboard',
            'name_l'    => 'ড্যাশবোর্ড',
            'web'       => 'dashboard',
            ''       => '',
            'web_icon'  => 'uil uil-home-alt',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],

        #Employees
        [
            'id'        =>  70,
            'parent'    =>  null,
            'name'      =>  'Employees',
            'name_l'    =>  'কর্মচারী',
            'web'       =>  'employees',
            'app'       =>  '',
            'web_icon'  =>  'uil uil-users-alt',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  71,
            'parent'    =>  70,
            'name'      =>  'Departments',
            'name_l'    =>  'বিভাগ',
            'web'       =>  'departments',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  72,
            'parent'    =>  70,
            'name'      =>  'Designations',
            'name_l'    =>  'পদবী',
            'web'       =>  'designations',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  73,
            'parent'    =>  70,
            'name'      =>  'Employees List',
            'name_l'    =>  'কর্মীদের তালিকা',
            'web'       =>  'employee-list',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        => 74,
            'parent'    => 70,
            'name'      => 'Attendance Sheet/Report',
            'name_l'    => 'উপস্থিতি শীট',
            'web'       =>  'attendance-sheet',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',    
        ],

        #Admin Section
        [
            'id'        => 100,
            'parent'    => null,
            'name'      => 'Admin Section',
            'name_l'    => 'অ্যাডমিন সেকশন',
            'web'       => 'admin-section',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 101,
            'parent'    => 100,
            'name'      => 'Admission Query',
            'name_l'    => 'ভর্তি অনুসন্ধান',
            'web'       => 'admission-query.index',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 102,
            'parent'    => 100,
            'name'      => 'Complaint',
            'name_l'    => 'অভিযোগ',
            'web'       => 'complaint.index',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 103,
            'parent'    => 100,
            'name'      => 'Phone Call Log',
            'name_l'    => 'ফোন কল লগ',
            'web'       => 'phone-call-log.index',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],

        #Academic section
        [
            'id'        => 150,
            'parent'    => null,
            'name'      => 'Academic Section',
            'name_l'    => 'একাডেমিক সেকশন',
            'web'       => 'academic-section',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 151,
            'parent'    => 150,
            'name'      => 'University',
            'name_l'    => 'বিশ্ববিদ্যালয়',
            'web'       => 'university.university',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 152,
            'parent'    => 150,
            'name'      => 'Subject',
            'name_l'    => 'বিষয়',
            'web'       => 'academic-subject.index',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 153,
            'parent'    => 150,
            'name'      => 'Assign Subjects',
            'name_l'    => 'বিষয় নির্ধারণ করুন',
            'web'       => 'academic-assign-subject.index',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],

        #Request new members
        [
            'id'        => 200,
            'parent'    => null,
            'name'      => 'Members',
            'name_l'    => 'সদস্য',
            'web'       => 'members',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 201,
            'parent'    => 200,
            'name'      => 'Requested Members',
            'name_l'    => 'অনুরোধিত সদস্য',
            'web'       => 'requested.members',
            'app'       => '',
            'web_icon'  => 'uil uil-user',
            'app_icon'  => '',
            'note'      => '',
            'note_l'    => '',
        ],
        [
            'id'        => 202,
            'parent'    => 200,
            'name'      => 'Member List',
            'name_l'    => 'সদস্যের তালিকা',
            'web'       => 'members.list',
            'app'       => '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        
        #User Settings start
        [
            'id'        =>  1000,
            'parent'    =>  null,
            'name'      =>  'User Settings',
            'name_l'    =>  'ব্যবহারকারী সেটিংস',
            'web'       =>  'settings',
            'app'       =>  '',
            'web_icon'  =>  'uil uil-cog',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  1001,
            'parent'    =>  1000,
            'name'      =>  'User Role',
            'name_l'    =>  'ব্যবহারকারীর ভূমিকা',
            'web'       =>  'roles',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  1002,
            'parent'    =>  1000,
            'name'      =>  'User\'s List',
            'name_l'    =>  'ব্যবহারকারীর তালিকা',
            'web'       =>  'users',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],

        #Communications
        [
            'id'        =>  2000,
            'parent'    =>  null,
            'name'      =>  'Communications',
            'name_l'    =>  'যোগাযোগ',
            'web'       =>  'communications',
            'app'       =>  '',
            'web_icon'  =>  'uil uil-cog',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  2001,
            'parent'    =>  2000,
            'name'      =>  'Notice Board',
            'name_l'    =>  'নোটিশ বোর্ড',
            'web'       =>  'notice-board',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  2002,
            'parent'    =>  2000,
            'name'      =>  'Send Email/Sms',
            'name_l'    =>  'ইমেইল/এসএমএস পাঠান',
            'web'       =>  'send-email-or-sms',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  2003,
            'parent'    =>  2000,
            'name'      =>  'Event',
            'name_l'    =>  'ইভেন্ট',
            'web'       =>  'event',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  2004,
            'parent'    =>  2000,
            'name'      =>  'Calendar',
            'name_l'    =>  'ক্যালেন্ডার',
            'web'       =>  'calendar',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  2005,
            'parent'    =>  2000,
            'name'      =>  'Email Template',
            'name_l'    =>  'ইমেইল টেম্পলেট',
            'web'       =>  'email-template',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  2006,
            'parent'    =>  2000,
            'name'      =>  'SMS Template',
            'name_l'    =>  'এসএমএস টেম্পলেট',
            'web'       =>  'sms-template',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],

        #Accounts
        [
            'id'        =>  3000,
            'parent'    =>  null,
            'name'      =>  'Accounts',
            'name_l'    =>  'হিসাব',
            'web'       =>  'accounts',
            'app'       =>  '',
            'web_icon'  =>  'uil uil-cog',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  3001,
            'parent'    =>  3000,
            'name'      =>  'Profit & Loss',
            'name_l'    =>  'লাভ ও ক্ষতি',
            'web'       =>  'profit-and-loss',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  3002,
            'parent'    =>  3000,
            'name'      =>  'Bank Account',
            'name_l'    =>  'ব্যাংক হিসাব',
            'web'       =>  'bank-accounts',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  3003,
            'parent'    =>  3000,
            'name'      =>  'Chart Of Account',
            'name_l'    =>  'হিসাবের চার্ট',
            'web'       =>  'chart-of-accounts',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  3004,
            'parent'    =>  3000,
            'name'      =>  'Income',
            'name_l'    =>  'আয়',
            'web'       =>  'incomes',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  3005,
            'parent'    =>  3000,
            'name'      =>  'Expense',
            'name_l'    =>  'ব্যয়',
            'web'       =>  'expenses',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],

        #inventory
        [
            'id'        =>  4000,
            'parent'    =>  null,
            'name'      =>  'Inventory',
            'name_l'    =>  'ইনভেন্টরি',
            'web'       =>  'inventory',
            'app'       =>  '',
            'web_icon'  =>  'uil uil-cog',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  4001,
            'parent'    =>  4000,
            'name'      =>  'Item Category',
            'name_l'    =>  'আইটেম ক্যাটাগরি',
            'web'       =>  'item-category',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  4002,
            'parent'    =>  4000,
            'name'      =>  'Item List',
            'name_l'    =>  'আইটেম তালিকা',
            'web'       =>  'item-list',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  4003,
            'parent'    =>  4000,
            'name'      =>  'Item Store',
            'name_l'    =>  'আইটেম স্টোর',
            'web'       =>  'item-store',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  4004,
            'parent'    =>  4000,
            'name'      =>  'Supplier',
            'name_l'    =>  'সরবরাহকারী',
            'web'       =>  'suppliers',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  4005,
            'parent'    =>  4000,
            'name'      =>  'Item Receive',
            'name_l'    =>  'আইটেম প্রাপ্তি',
            'web'       =>  'item-receive',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  4006,
            'parent'    =>  4000,
            'name'      =>  'Item Sell',
            'name_l'    =>  'আইটেম বিক্রি',
            'web'       =>  'item-sell',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  4007,
            'parent'    =>  4000,
            'name'      =>  'Item Issue',
            'name_l'    =>  'আইটেম ইস্যু',
            'web'       =>  'item-issue',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],


        #General Settings
        [
            'id'        =>  5000,
            'parent'    =>  null,
            'name'      =>  'General Settings',
            'name_l'    =>  'সাধারণ সেটিংস',
            'web'       =>  'general-settings',
            'app'       =>  '',
            'web_icon'  =>  'uil uil-cog',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5001,
            'parent'    =>  5000,
            'name'      =>  'Country',
            'name_l'    =>  'দেশ',
            'web'       =>  'country.index',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5002,
            'parent'    =>  5000,
            'name'      =>  'City',
            'name_l'    =>  'শহর',
            'web'       =>  'city.index',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5003,
            'parent'    =>  5000,
            'name'      =>  'Holiday',
            'name_l'    =>  'ছুটি',
            'web'       =>  'holidays',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5004,
            'parent'    =>  5000,
            'name'      =>  'Notification Settings',
            'name_l'    =>  'নোটিফিকেশন সেটিংস',
            'web'       =>  'notification-settings',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5005,
            'parent'    =>  5000,
            'name'      =>  'Email Settings',
            'name_l'    =>  'ইমেইল সেটিংস',
            'web'       =>  'email-settings',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5006,
            'parent'    =>  5000,
            'name'      =>  'Tawk To',
            'name_l'    =>  'টক টু',
            'web'       =>  'tawk.to.index',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5007,
            'parent'    =>  5000,
            'name'      =>  'Messenger Chat',
            'name_l'    =>  'মেসেঞ্জার চ্যাট',
            'web'       =>  'messenger-chat',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5008,
            'parent'    =>  5000,
            'name'      =>  'Manage Currency',
            'name_l'    =>  'মুদ্রা পরিচালনা',
            'web'       =>  'manage-currency',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],

        [
            'id'        =>  5009,
            'parent'    =>  5000,
            'name'      =>  'Backup ',
            'name_l'    =>  'ব্যাকআপ',
            'web'       =>  'backup',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],

        [
            'id'        =>  5010,
            'parent'    =>  5000,
            'name'      =>  'Language',
            'name_l'    =>  'ভাষা',
            'web'       =>  'language',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5011,
            'parent'    =>  5000,
            'name'      =>  'Language Setup',
            'name_l'    =>  'ভাষা সেটআপ',
            'web'       =>  'language-setup',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5012,
            'parent'    =>  5000,
            'name'      =>  'Preloader Settings',
            'name_l'    =>  'প্রিলোডার সেটিংস',
            'web'       =>  'preloader-settings',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5013,
            'parent'    =>  5000,
            'name'      =>  'Configuration',
            'name_l'    =>  'কনফিগারেশন',
            'web'       =>  'configuration',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  5014,
            'parent'    =>  5000,
            'name'      =>  'Weekend',
            'name_l'    =>  'উইকেন্ড',
            'web'       =>  'weekend.index',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        # frontend
        [
            'id'        =>  6000,
            'parent'    =>  null,
            'name'      =>  'Frontend',
            'name_l'    =>  'ফ্রন্টএন্ড',
            'web'       =>  'frontend-settings',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
        [
            'id'        =>  6001,
            'parent'    =>  6000,
            'name'      =>  'Articles',
            'name_l'    =>  'আর্টিকেল',
            'web'       =>  'frontend.article.index',
            'app'       =>  '',
            'web_icon'  =>  '',
            'app_icon'  =>  '',
            'note'      =>  '',
            'note_l'    =>  '',
        ],
    ];
    #$all_menus_parent_id = [1,2,3,4,5,6,70,71,72,73,74,100,101,102,103,150,151,152,153,200,201,202,1000,1001,1002,2000,2001,2002,2003,2004,2005,2006,3000,3001,3002,3003,3004,3005,4000,4001,4002,4003,4004,4005,4006,4007,5000,5001,5002,5003,5004,5005,5006,5007,5008,5009,5010,5011,5012,5013,5014,6000,6001];
    public function up(): void
    {
        Schema::create('menus', function (Blueprint $table) {
            $table->id();
            $table->integer('parent')->nullable();
            $table->string('name')->collation('utf16_general_ci');
            $table->string('name_l')->collation('utf16_general_ci');

            $table->string('web')->nullable();
            $table->string('web_icon')->nullable();
            
            $table->string('app')->nullable();
            $table->string('app_icon')->nullable();

            $table->string('note')->nullable();
            $table->string('note_l')->nullable();
            $table->timestamps();
        });
        DB::table('menus')->insert($this->data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('menus');
    }
};
